import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { integrity } from '@/components/rivet/integrity/client';
import { DOMAINS, modelLabel } from '@/components/rivet/evalModels';
import EvidenceLink from '@/components/rivet/integrity/EvidenceLink';
export default function LeaderboardCard({ onNavigate }) {
  const [domain, setDomain] = useState('biology');
  const q = useQuery({ queryKey: ['integrity-rankings', domain, true], queryFn: () => integrity('rankings', { domain, official: true }), refetchInterval: 30000 });
  return <section className="dark text-foreground bg-card border border-border rounded-2xl p-4 space-y-3"><div className="flex justify-between gap-2"><h3 className="font-semibold text-sm">Official domain rankings</h3><button className="text-xs underline" onClick={() => onNavigate?.('capability-map')}>Explore</button></div><select aria-label="Leaderboard domain" value={domain} onChange={e => setDomain(e.target.value)} className="w-full rounded-lg bg-background border p-2 text-xs">{DOMAINS.map(d => <option key={d.id} value={d.id}>{d.label}</option>)}</select>{q.isLoading ? <p className="text-xs">Loading…</p> : q.isError ? <p role="alert" className="text-xs">Rankings unavailable.</p> : q.data.rows.length === 0 ? <p className="text-xs text-muted-foreground">No eligible rankings yet. Inspect exploratory evidence in the Capability Map.</p> : q.data.rows.slice(0, 5).map(r => <div key={r.modelId} className="text-xs space-y-1 border-t pt-2"><p>{modelLabel(r.modelId)} · {r.avg?.toFixed(1) ?? '—'}/100</p><p className="text-muted-foreground">{r.label} · n={r.n} families · {r.runCount} runs · CI {r.ci ? r.ci.map(n => n.toFixed(1)).join('–') : 'unavailable'}</p><p>{r.methodologyVersion}</p>{r.history[0] && <EvidenceLink resultId={r.history[0].id} />}</div>)}</section>;
}