import React, { useEffect, useState } from 'react';
import { Loader2, ShieldCheck } from 'lucide-react';

export default function ReleaseGatePanel({ tests, gate, onOpenExperts }) {
  const [agentName, setAgentName] = useState(''), [version, setVersion] = useState(''), [evidenceUri, setEvidenceUri] = useState(''), [decisions, setDecisions] = useState({});
  useEffect(() => setDecisions(current => Object.fromEntries(tests.map(test => [test.id, current[test.id] || '']))), [tests]);
  const complete = tests.length > 0 && tests.every(test => decisions[test.id]);
  const submit = () => gate.mutate({ agentName, version, results: tests.map(test => ({ testId: test.id, passed: decisions[test.id] === 'pass', evidenceUri })) }, { onSuccess: () => { setAgentName(''); setVersion(''); setEvidenceUri(''); setDecisions({}); } });
  return <section className="rounded-2xl border border-[#2f3336] bg-[#16181c] p-5 space-y-4"><div><h2 className="flex items-center gap-2 text-sm font-bold text-white"><ShieldCheck size={16} className="text-[#b06d97]" /> Release gate</h2><p className="mt-1 text-xs text-[#71767b]">Every active expert-verified regression test must pass. Missing results block the release.</p></div>
    {!tests.length ? <p className="text-xs text-[#71767b]">No active regression tests exist. <button onClick={onOpenExperts} className="text-white underline">Review a failure in Expert Workspace</button> to create one.</p> : <>
      <div className="grid gap-2 sm:grid-cols-2"><input value={agentName} onChange={e => setAgentName(e.target.value)} placeholder="System or agent name" className="rounded-xl border border-[#2f3336] bg-black px-3 py-2 text-sm text-white" /><input value={version} onChange={e => setVersion(e.target.value)} placeholder="Immutable version" className="rounded-xl border border-[#2f3336] bg-black px-3 py-2 text-sm text-white" /></div>
      <input value={evidenceUri} onChange={e => setEvidenceUri(e.target.value)} placeholder="CI run or evidence reference (optional)" className="w-full rounded-xl border border-[#2f3336] bg-black px-3 py-2 text-sm text-white" />
      <div className="divide-y divide-[#2f3336] border-y border-[#2f3336]">{tests.map(test => <div key={test.id} className="flex flex-col gap-2 py-3 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-xs font-semibold text-white">{test.name}</p><p className="text-[10px] uppercase text-[#71767b]">{test.severity || 'medium'} · {test.verifiedByExpertName || 'expert verified'}</p></div><div className="flex gap-2">{['pass','fail'].map(value => <button key={value} onClick={() => setDecisions(all => ({ ...all, [test.id]: value }))} className={`rounded-full border px-3 py-1 text-xs font-bold capitalize ${decisions[test.id] === value ? value === 'pass' ? 'border-emerald-500 bg-emerald-500/15 text-emerald-400' : 'border-red-500 bg-red-500/15 text-red-400' : 'border-[#2f3336] text-[#71767b]'}`}>{value}</button>)}</div></div>)}</div>
      <button onClick={submit} disabled={gate.isPending || !agentName.trim() || !version.trim() || !complete} className="flex items-center gap-2 rounded-full bg-[#653653] px-4 py-2 text-xs font-bold text-white disabled:opacity-40">{gate.isPending && <Loader2 size={13} className="animate-spin" />} Evaluate release</button>
    </>}{gate.isError && <p role="alert" className="text-xs text-red-400">{gate.error?.response?.data?.error || gate.error.message}</p>}</section>;
}