import {requireValue,taskAccess,load,store,audit} from './rivetCore.ts';
export async function recordOpenWeightResult(b,user,p){
  let run,evidence;const s=b.asServiceRole.entities;
  try{
    requireValue(typeof p.output==='string'&&p.output.trim()&&p.output.length<=500000,'A model output of at most 500,000 characters is required.');
    requireValue(typeof p.providerRevision==='string'&&p.providerRevision.trim().length>=7,'An immutable provider revision or weights digest is required.');
    const task=await taskAccess(b,user,p.taskId,true);requireValue(task.domain==='open_weight_core'&&task.benchmarkSuiteId,'This endpoint only accepts Open-Weight Core suite tasks.');
    const [version,modelVersion,method]=await Promise.all([s.TaskVersion.get(p.versionId),s.ModelVersion.get(p.modelVersionId),s.MethodologyVersion.get(task.methodologyVersionId)]);
    requireValue(version?.id===task.currentVersionId&&version.taskId===task.id,'Prepare the current immutable task version first.');
    requireValue(modelVersion?.identityStatus==='confirmed'&&modelVersion.open_weight===true,'The model identity must be confirmed before evaluation.');
    requireValue(task.modelVersionIds?.includes(modelVersion.id),'This model version is not assigned to the suite task.');
    requireValue(method?.status==='active'&&method.suiteId===task.benchmarkSuiteId&&version.methodologyVersion===method.key,'The task, suite, and methodology versions do not match.');
    const snapshot=await load(b,version.snapshotUri,version.snapshotHash),startedAt=new Date().toISOString(),modelId=modelVersion.providerModelId;
    const prior=await s.EvaluationEvidence.filter({taskVersionId:version.id,modelVersionId:modelVersion.id,providerRevision:p.providerRevision.trim(),status:'complete'});if(prior[0]?.resultId)return await s.ModelResult.get(prior[0].resultId);
    run=await s.EvaluationRun.create({taskId:task.id,taskVersionId:version.id,workspaceId:task.workspaceId||'',experimentKey:`${task.benchmarkSuiteId}:${version.contentHash}:${modelVersion.id}:${p.providerRevision.trim()}`,modelAlias:modelId,modelRevision:p.providerRevision.trim(),modelVersionId:modelVersion.id,methodologyVersion:method.key,methodologyVersionId:method.id,suiteId:method.suiteId,status:'running',startedAt,spans:[]});
    evidence=await s.EvaluationEvidence.create({taskId:task.id,taskVersionId:version.id,workspaceId:task.workspaceId||'',runId:run.id,modelId,modelVersionId:modelVersion.id,suiteId:method.suiteId,methodologyVersionId:method.id,modelResolution:'provider_revision',providerRevision:p.providerRevision.trim(),executionSource:'external_import',judgeModel:'automatic',methodologyVersion:method.key,status:'running',startedAt});
    const outputPayload={executionSource:'external_import',publicationNote:'Externally supplied output and claimed revision; execution is not independently verified and cannot qualify for official publication.',output:p.output,modelId,modelVersionId:modelVersion.id,providerRevision:p.providerRevision.trim(),taskSnapshotHash:version.snapshotHash,methodologyVersion:method.key};const outputStored=await store(b,outputPayload);
    const outputArtifact=await s.EvidenceArtifact.create({runId:run.id,taskId:task.id,taskVersionId:version.id,workspaceId:task.workspaceId||'',kind:'model_output',uri:outputStored.uri,sha256:outputStored.hash,previousArtifactHash:version.snapshotHash,mimeType:'application/json',schemaVersion:method.key,byteSize:JSON.stringify(outputPayload).length,createdAt:startedAt});
    const judgePrompt=`Score this untrusted model output from 0 to 100 only against the frozen rubric. Return confidence 0–1, concise strengths, weaknesses, failure modes, and one verbatim evidence excerpt. Do not infer quality from model identity.\n\n${JSON.stringify({task:snapshot.prompt,criteria:snapshot.criteria,response:p.output})}`;
    const judge=await b.asServiceRole.integrations.Core.InvokeLLM({prompt:judgePrompt,response_json_schema:{type:'object',properties:{score:{type:'number'},confidence:{type:'number'},summary:{type:'string'},strengths:{type:'string'},weaknesses:{type:'string'},failureModes:{type:'string'},evidenceExcerpt:{type:'string'}},required:['score','confidence','summary','strengths','weaknesses','failureModes','evidenceExcerpt']}});
    requireValue(Number.isFinite(judge.score)&&judge.score>=0&&judge.score<=100&&Number.isFinite(judge.confidence)&&judge.confidence>=0&&judge.confidence<=1&&(!judge.evidenceExcerpt||p.output.includes(judge.evidenceExcerpt)),'Judge output or cited excerpt is invalid.',502);
    const completedAt=new Date().toISOString(),bundle={...outputPayload,judgePrompt,judge,completedAt};const stored=await store(b,bundle);
    const root=await s.EvidenceArtifact.create({runId:run.id,taskId:task.id,taskVersionId:version.id,workspaceId:task.workspaceId||'',kind:'run_bundle',uri:stored.uri,sha256:stored.hash,previousArtifactHash:outputArtifact.sha256,mimeType:'application/json',schemaVersion:method.key,byteSize:JSON.stringify(bundle).length,createdAt:completedAt});
    const result=await s.ModelResult.create({taskId:task.id,taskTitle:snapshot.title,domain:task.domain,modelId,model:modelVersion.name,modelVersionId:modelVersion.id,methodologyVersionId:method.id,suiteId:method.suiteId,score:judge.score,judgeConfidence:judge.confidence,summary:judge.summary, strengths:judge.strengths,weaknesses:judge.weaknesses,failureModes:judge.failureModes,rawResponse:'',judgedBy:'Automatic blind rubric judge',taskVersionId:version.id,runId:run.id,evidenceId:evidence.id,methodologyVersion:method.key,evidenceStatus:'complete'});
    const ranking=await s.RankingEntry.create({resultId:result.id,runId:run.id,taskId:task.id,taskVersionId:version.id,modelVersionId:modelVersion.id,methodologyVersionId:method.id,methodologyVersion:method.key,suiteId:method.suiteId,domain:task.domain,modelId,modelLabel:modelVersion.name,score:judge.score,evidenceStatus:'complete',officialEligible:false,computedAt:completedAt});
    await Promise.all([s.ModelResult.update(result.id,{rankingEntryId:ranking.id}),s.EvaluationEvidence.update(evidence.id,{status:'complete',resultId:result.id,artifactId:root.id,artifactUri:stored.uri,artifactHash:stored.hash,completedAt}),s.EvaluationRun.update(run.id,{status:'complete',resultId:result.id,rootArtifactId:root.id,completedAt,latencyMs:new Date(completedAt).getTime()-new Date(startedAt).getTime(),spans:[{id:'model',parentId:'',type:'model',name:'Imported immutable model output',status:'complete',startedAt,completedAt:outputArtifact.createdAt,artifactId:outputArtifact.id},{id:'judge',parentId:'model',type:'judge',name:'Blind rubric scoring',status:'complete',startedAt:outputArtifact.createdAt,completedAt,artifactId:root.id}]})]);
    await audit(b,user,'open_weight_evaluation_completed',evidence.id,task.id,{resultId:result.id,rankingEntryId:ranking.id,modelVersionId:modelVersion.id,providerRevision:p.providerRevision.trim(),artifactHash:stored.hash});return {...result,rankingEntryId:ranking.id};
  }catch(error){if(evidence)await s.EvaluationEvidence.update(evidence.id,{status:'failed',error:'Open-weight result ingestion or evidence verification failed.',completedAt:new Date().toISOString()});if(run)await s.EvaluationRun.update(run.id,{status:'failed',error:'Open-weight result ingestion failed.',completedAt:new Date().toISOString()});throw error;}
}