export const REPORT_VERSION='rivet-domain-report-1.0';
export const REPORT_TEMPLATES=[
  {id:'domain_brief',title:'Domain evidence brief',description:'An executive-ready domain summary with model comparisons, uncertainty, and source references.',sections:['Executive summary','Domain comparison','Methodology','Verification and limitations','Evidence register','Audit references']},
  {id:'technical_report',title:'Technical evaluation report',description:'A reproducible research-style report covering cohort selection, calibration, and evidence provenance.',sections:['Executive summary','Methodology','Domain comparison','Judge calibration','Verification and limitations','Evidence register','Audit references']},
  {id:'audit_dossier',title:'Verification dossier',description:'An audit-first record of eligibility checks, reviewed evidence, and the resulting domain snapshot.',sections:['Verification and limitations','Audit references','Evidence register','Domain comparison','Judge calibration','Methodology']}
];
const text=x=>String(x??'Unavailable').replace(/[\r\n|]/g,' ').replace(/([\\`*_{}\[\]<>#])/g,'\\$1');
const num=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'Unavailable';
export const REPORT_METHOD='Public tasks only; latest eligible result per normalized-prompt family on identical task snapshot hashes shared across all included model revisions. Each resolved provider revision is separate. Final adjudicated scores, equal family weights, 2,000 bootstrap resamples with seed 72431 and 95% percentile intervals. At least 50 families and interval width ≤10 are required for a verified aggregate; official evidence eligibility alone is not a sample-size guarantee.';
export const REPORT_LIMITATIONS=['This is an as-of snapshot, not a claim about subsequent evaluations or credential changes.','Confidence intervals describe the sampled task families, not all tasks in the domain; duplicate-prompt families are only a proxy for independence.','Human review is observational and non-blinded; automatic judge revisions may remain unresolved and self-reported confidence is not held-out calibration.','No-match contamination checks only cover the recorded scope; they do not prove absence of training-data contamination.','Audit events are corroborating application records, not independent certification; SHA-256 detects changed bytes but is not a digital signature or WORM storage.','Citation links require sign-in and current permission to read every source task. No DOI is registered and no overall intelligence score is calculated.'];
export function reportMarkdown(m){
  const matrix=['| Model / provider revision | Final score / 100 | 95% CI | Families | Sample status |','|---|---:|---|---:|---|',...m.rows.map(r=>`| ${text(r.modelAlias)} / ${text(r.modelRevision)} | ${num(r.avg)} | ${r.ci?r.ci.map(x=>num(x)).join('–'):'Unavailable'} | ${r.n} | ${text(r.label)} |`)].join('\n');
  const calibration=['| Diagnostic | Value |','|---|---:|',...Object.entries({'Paired adjudications':m.metrics.calibrationResults,'Judge–human kappa':m.metrics.cohenKappa,'Reviewer alpha':m.metrics.krippendorffAlpha,'Mean absolute score error':m.metrics.meanAbsoluteError,'Signed score bias':m.metrics.meanSignedError,'Score error variance':m.metrics.scoreErrorVariance,'Brier score':m.metrics.brierScore,'ECE':m.metrics.ece}).map(([k,v])=>`| ${k} | ${num(v,3)} |`),'','Repeated-judge variance: unavailable. These diagnostics use only the cited cohort; all missing values remain unavailable.'].join('\n');
  const audit=m.audits.map(a=>`- **${text(a.action)}** · ${text(a.occurredAt)} · audit ${text(a.id)} · target ${text(a.targetId)}`).join('\n');
  const evidence=m.evidence.map((e,i)=>`### E${i+1} · ${text(e.taskTitle)}\n\n[Inspect current evidence](/evidence?result=${encodeURIComponent(e.resultId)}) · result ${text(e.resultId)}\n\n- Requested model: ${text(e.modelAlias)}; revision: ${text(e.providerRevision)}\n- Task version: ${text(e.taskVersionId)}; snapshot SHA-256: ${e.taskSnapshotHash}\n- Output SHA-256: ${e.outputHash}; bundle SHA-256: ${e.bundleHash}\n- Automated score: ${num(e.automatedScore)}; final human score: ${num(e.finalScore)}\n- Review IDs: ${e.reviews.map(r=>text(r.id)).join(', ')}; final adjudication: ${text(e.finalId)}\n- Quality assessment: ${text(e.qualityId)}; scope: ${text(e.contaminationScope)}\n- Linked audit IDs: ${e.auditIds.map(text).join(', ')}`).join('\n\n');
  const exclusions=Object.entries(m.exclusions).map(([reason,n])=>`- ${text(reason)}: ${n}`).join('\n');
  const blocks={'Executive summary':`${text(m.domainLabel)} snapshot with ${m.evidence.length} cited results across ${m.rows.length} resolved model revisions and ${m.rows[0]?.n||0} matched task families. All cited results passed the official-evidence report gate; sample status is reported separately.\n\nEvidence cutoff: ${m.cutoffAt}. Latest contributing audit: ${m.latestAuditAt}.`,'Domain comparison':matrix,'Methodology':m.methodology+'\n\nScoring methodology: '+m.methodologyVersion+'; statistics: '+m.metrics.statisticsVersion+'; template: '+m.templateVersion+'.','Judge calibration':calibration,'Verification and limitations':`Scope: ${m.totalResults} domain results considered; ${m.eligibleResults} passed eligibility before cohort matching; ${m.evidence.length} cited. Exclusion counts can overlap.\n\n${exclusions||'No eligibility exclusions.'}\n\n${m.limitations.map(x=>'- '+x).join('\n')}`,'Evidence register':evidence,'Audit references':audit};
  return `# ${m.title}\n\n${m.template.title} · official evidence only · generated ${m.generatedAt}\n\nEvidence cutoff: ${m.cutoffAt} · Latest contributing audit: ${m.latestAuditAt}\n\n`+m.template.sections.map(section=>`## ${section}\n\n${blocks[section]}`).join('\n\n');
}